CREATE TABLE User (
    UserEmail VARCHAR(45) UNIQUE NOT NULL,
    UserPassword VARCHAR(32) NOT NULL,
    UserName VARCHAR(45) NOT NULL,
    UserSurname VARCHAR(45) NOT NULL,
    UserPhone VARCHAR(13) UNIQUE NOT NULL,
    StartDate DATE NOT NULL,
    PRIMARY KEY (UserEmail)
);

CREATE TABLE Grup (
    GrupName VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (GrupName)
);

CREATE TABLE City (
	CityName VARCHAR(45) NOT NULL UNIQUE,
    PRIMARY KEY (CityName)
);

CREATE TABLE District (
	DistrictID INT NOT NULL UNIQUE AUTO_INCREMENT,
	DistrictName VARCHAR(45) NOT NULL,
    CityName VARCHAR(45) NOT NULL,
    PRIMARY KEY (DistrictID),
    FOREIGN KEY (CityName) REFERENCES City (CityName) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Village (
	VillageID INT NOT NULL UNIQUE AUTO_INCREMENT,
    VillageName VARCHAR(45) NOT NULL,
    DistrictID INT NOT NULL,
    PRIMARY KEY (VillageID),
    FOREIGN KEY (DistrictID) REFERENCES District (DistrictID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ProductType (
    ProductTypeName VARCHAR(45) UNIQUE NOT NULL,
    PRIMARY KEY (ProductTypeName)
);

CREATE TABLE Farmer (
	TCID VARCHAR(15) NOT NULL UNIQUE,
    FarmerName VARCHAR(45) NOT NULL,
    FarmerSurname VARCHAR(45) NOT NULL,
    GrupName VARCHAR(20),
	Phone VARCHAR(15) NOT NULL,
    StartDate DATE NOT NULL,
    PRIMARY KEY (TCID),
    FOREIGN KEY (GrupName) REFERENCES Grup (GrupName) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Product (
	ProductID INT UNIQUE NOT NULL AUTO_INCREMENT,
    TCID VARCHAR(11) NOT NULL,
    ProductTypeName VARCHAR(45) NOT NULL,
	VillageID INT NOT NULL,
    Size FLOAT NOT NULL,
    PlaceList VARCHAR(256) NOT NULL,
    PRIMARY KEY (ProductID),
    FOREIGN KEY (TCID) REFERENCES Farmer (TCID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (VillageID) REFERENCES Village (VillageID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ProductTypeName) REFERENCES ProductType (ProductTypeName) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Bill (
	BillID INT UNIQUE NOT NULL AUTO_INCREMENT,
	BillAmount FLOAT NOT NULL,
	BillDescription VARCHAR(60) NOT NULL,
	BillDate DATE NOT NULL,
	BillYear YEAR NOT NULL,
	PRIMARY KEY (BillID)
);

CREATE TABLE FarmerPayment (
	PaymentID INT UNIQUE NOT NULL AUTO_INCREMENT,
	TCID VARCHAR(15) NOT NULL,
	Money FLOAT NOT NULL,
	PaymentDate DATE NOT NULL,
	PaymentYear YEAR NOT NULL,
	PRIMARY KEY (PaymentID),
	FOREIGN KEY (TCID) REFERENCES Farmer (TCID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AnalysisStatus (
	AnalysisStatusID INT UNIQUE NOT NULL AUTO_INCREMENT,
	AnalysisStatusDescription VARCHAR(24) NOT NULL,
	PRIMARY KEY (AnalysisStatusID)
);

CREATE TABLE AnalysisType (
	AnalysisTypeName VARCHAR(10) UNIQUE NOT NULL,
	PRIMARY KEY (AnalysisTypeName)
);

CREATE TABLE Analysis (
	AnalysisID INT UNIQUE NOT NULL AUTO_INCREMENT,
	ProductID INT NOT NULL,
	AnalysisTypeName VARCHAR(10) NOT NULL,
	AnalysisStatusID INT NOT NULL,
	AnalysisDate DATE NOT NULL,
	AnalysisYear YEAR NOT NULL,
	PRIMARY KEY (AnalysisID),
	FOREIGN KEY (ProductID) REFERENCES Product (ProductID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (AnalysisTypeName) REFERENCES AnalysisType (AnalysisTypeName) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (AnalysisStatusID) REFERENCES AnalysisStatus (AnalysisStatusID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO User (UserName, UserSurname, UserEmail, UserPhone, UserPassword, StartDate) VALUES ('Anıl', 'Doğru', 'anildogru07@gmail.com', '5069540105', 'c8837b23ff8aaa8a2dde915473ce0991', now());